name: "sast-scan"

on:
  push:
    branches: [master]

jobs:
  Bearer-Scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Installation
      run: |
       curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
    - name: Bearer Scan
      run: |
       ./bin/bearer scan -f html --output ./shop.html .
    - name: Report Upload
      uses: actions/upload-artifact@v2
      with:
        name: sast report
        path: |
          ./shop.html